spring.application.name=cadastro
spring:
    aplication:
        name: connectionmongodb
    data:
    mongodb: "mongodb+srv://admin:2sZ5AcGt7DL4I36p@cluster0.iqkz0b2.mongodb.net/?appName=Cluster0"
    database: cadastro_aep